import type { ISkillCategory } from "@/components/skills/interfaces/skills.interface";

export const SKILL_CATEGORIES: ISkillCategory[] = [
  {
    id: 1,
    category: "Maquetación Web",
    skills: [
      {
        id: 1,
        names: ["HTML 5"],
        logo: "/assets/image/logo/conocimientos/html.webp",
        alt: "logo de HTML",
        width: 336,
        height: 336,
        url: "https://youtu.be/-oK6zL01fNM",
      },
      {
        id: 2,
        names: ["CSS 3"],
        logo: "/assets/image/logo/conocimientos/css.webp",
        alt: "logo de CSS",
        width: 336,
        height: 336,
        url: "https://youtu.be/K3xmRF8ab1o?si=TnCSUFSA5nbuh4_a",
      },
      {
        id: 3,
        names: ["Sass", "scss"],
        logo: "/assets/image/logo/conocimientos/sass.webp",
        alt: "logo de Sass",
        width: 394,
        height: 296,
        url: "https://sass-lang.com/documentation/",
      },
      {
        id: 4,
        names: ["Tailwind"],
        logo: "/assets/image/logo/conocimientos/tailwind.webp",
        alt: "logo de Tailwind",
        width: 360,
        height: 216,
        url: "https://youtu.be/R5EXap3vNDA?si=PUKQuP89JsRNuL7c",
      },
      {
        id: 5,
        names: ["Bootstrap"],
        logo: "/assets/image/logo/conocimientos/bootstrap.webp",
        alt: "logo de Bootstrap",
        width: 394,
        height: 314,
        url: "https://youtu.be/ng8ur8KNrpU?si=s6HhfgqoDqi4qy6l",
      },
      {
        id: 6,
        names: ["UI / UX", "Responsive Design"],
        logo: "/assets/image/logo/conocimientos/ui_ux.webp",
        alt: "logo de UI / UX",
        width: 336,
        height: 336,
        url: "https://youtu.be/udGrXWeJp1Y?si=-mJYkp1ECQIWlFbA",
      },
    ],
  },
  {
    id: 2,
    category: "Desarrollo Web",
    skills: [
      {
        id: 7,
        names: ["Angular"],
        logo: "/assets/image/logo/conocimientos/angular.webp",
        alt: "logo de Angular",
        width: 283,
        height: 300,
        url: "https://www.udemy.com/course/angular-fernando-herrera/",
      },
      {
        id: 8,
        names: ["RxJS"],
        logo: "/assets/image/logo/conocimientos/RxJS.webp",
        alt: "logo de RxJS",
        width: 336,
        height: 336,
        url: "https://www.udemy.com/course/angular-fernando-herrera/",
      },
      {
        id: 9,
        names: ["React"],
        logo: "/assets/image/logo/conocimientos/react.webp",
        alt: "logo de React JS",
        width: 386,
        height: 336,
        url: "https://www.udemy.com/course/react-cero-experto/",
      },
      {
        id: 10,
        names: ["Next JS"],
        logo: "/assets/image/logo/conocimientos/next.webp",
        alt: "logo de Next JS",
        width: 300,
        height: 300,
        url: "https://www.udemy.com/course/nextjs-fh/",
      },
      {
        id: 11,
        names: ["Consumo de APIs REST"],
        logo: "/assets/image/logo/conocimientos/API.webp",
        alt: "logo de API REST",
        width: 336,
        height: 336,
        url: "https://youtu.be/i8sr--1D13Y?si=L4NEHHrhPZKD28nP",
      },
    ],
  },
  {
    id: 3,
    category: "Desarrollo Móvil",
    skills: [
      {
        id: 12,
        names: ["Ionic"],
        logo: "/assets/image/logo/conocimientos/ionic.webp",
        alt: "logo de Ionic",
        width: 336,
        height: 336,
        url: "https://ionicframework.com/docs",
      },
      {
        id: 13,
        names: ["Capacitor"],
        logo: "/assets/image/logo/conocimientos/capacitor.webp",
        alt: "logo de Capacitor",
        width: 300,
        height: 300,
        url: "https://capacitorjs.com/",
      },
      {
        id: 14,
        names: ["Cordova"],
        logo: "/assets/image/logo/conocimientos/cordova.webp",
        alt: "logo de Cordova",
        width: 256,
        height: 256,
        url: "https://cordova.apache.org/",
      },
      {
        id: 15,
        names: ["React Native"],
        logo: "/assets/image/logo/conocimientos/react.webp",
        alt: "logo de React Native",
        width: 386,
        height: 336,
        url: "https://www.udemy.com/course/react-native-expo/",
      },
      {
        id: 16,
        names: ["Expo"],
        logo: "/assets/image/logo/conocimientos/expo.webp",
        alt: "logo de Expo",
        width: 295,
        height: 261,
        url: "https://www.udemy.com/course/react-native-expo/",
      },
    ],
  },
  {
    id: 4,
    category: "Lenguajes de Programación",
    skills: [
      {
        id: 17,
        names: ["JavaScript"],
        logo: "/assets/image/logo/conocimientos/javascript.webp",
        alt: "logo de JavaScript",
        width: 336,
        height: 336,
        url: "https://www.youtube.com/playlist?list=PLvq-jIkSeTUZ6QgYYO3MwG9EMqC-KoLXA",
      },
      {
        id: 18,
        names: ["TypeScript"],
        logo: "/assets/image/logo/conocimientos/typescript.webp",
        alt: "logo de TypeScript",
        width: 336,
        height: 336,
        url: "https://www.udemy.com/course/typescript-guia-completa/",
      },
    ],
  },
  {
    id: 5,
    category: "Inteligencia Artificial",
    skills: [
      {
        id: 19,
        names: ["Claude Code"],
        logo: "/assets/image/logo/conocimientos/claude_code.webp",
        alt: "logo de Claude Code",
        width: 336,
        height: 336,
        url: "https://www.udemy.com/course/claude-code-guia-completa/",
      },
    ],
  },
  {
    id: 6,
    category: "Nube y Despliegue",
    skills: [
      {
        id: 20,
        names: ["Vercel"],
        logo: "/assets/image/logo/conocimientos/vercel.webp",
        alt: "logo de Vercel",
        width: 360,
        height: 360,
        url: "https://vercel.com/docs",
      },
      {
        id: 21,
        names: ["Amazon Web Services"],
        logo: "/assets/image/logo/conocimientos/aws_light.webp",
        logoDark: "/assets/image/logo/conocimientos/aws_dark.webp",
        alt: "logo de AWS",
        width: 394,
        height: 236,
        widthDark: 394,
        heightDark: 244,
        url: "https://youtu.be/zQyrhjEAqLs?si=plYsshR_1zXqN5YH",
      },
    ],
  },
  {
    id: 7,
    category: "Control de Versiones",
    skills: [
      {
        id: 22,
        names: ["Git"],
        logo: "/assets/image/logo/conocimientos/git.webp",
        alt: "logo de Git",
        width: 336,
        height: 336,
        url: "https://www.udemy.com/course/git-github/",
      },
      {
        id: 23,
        names: ["GitHub"],
        logo: "/assets/image/logo/conocimientos/github.webp",
        alt: "logo de GitHub",
        width: 349,
        height: 336,
        url: "https://github.com/DanielPinedaM/",
      },
    ],
  },
];
