import type { TExperience } from '@/types/portfolio.types';

export const EXPERIENCE: TExperience[] = [
  {
    id: 1,
    company: 'TASS COL',
    role: 'Desarrollador Frontend y Móvil',
    date: 'Octubre 2023 - Julio 2026',
    logoLight: '/assets/image/logo/experiencia/TASS-COL/TASS-11.png',
    logoDark: '/assets/image/logo/experiencia/TASS-COL/TASS-1.png',
    alt: 'logo de Telemetry And Security Systems (TASS COL)',
    url: 'https://www.tasstech.co/',
    logoWidth: 'max-w-22.5',
    width: 740,
    height: 846,
  },
  {
    id: 2,
    company: 'Different Roads',
    role: 'Desarrollador frontend',
    date: 'Junio 2022 - Septiembre 2023',
    logoLight: '/assets/image/logo/experiencia/different_roads.png',
    logoDark: '/assets/image/logo/experiencia/different_roads.png',
    alt: 'logo de Different Roads',
    url: 'https://www.differentroads.es/',
    logoWidth: 'max-w-22.5',
    width: 491,
    height: 491,
  },
  {
    id: 3,
    company: 'Bancolombia',
    role: 'Desarrollador de Automatización',
    date: 'Octubre 2021 - Mayo 2022',
    logoLight: '/assets/image/logo/experiencia/bancolombia.png',
    logoDark: '/assets/image/logo/experiencia/bancolombia.png',
    alt: 'logo de Bancolombia',
    url: 'https://www.bancolombia.com/personas',
    logoWidth: 'max-w-23.75',
    width: 1000,
    height: 1000,
  },
];
