import type { TSkill } from "@/types/portfolio.types";

export const SKILLS: TSkill[] = [
  {
    id: 1,
    names: ["Git"],
    logo: "/assets/image/logo/conocimientos/git.png",
    alt: "logo de Git",
    width: 431,
    height: 431,
    url: "https://www.udemy.com/course/git-github/",
  },
  {
    id: 2,
    names: ["GitHub"],
    logo: "/assets/image/logo/conocimientos/github.png",
    alt: "logo de GitHub",
    width: 522,
    height: 503,
    url: "https://github.com/DanielPinedaM/",
  },
  /* {
    id: 3,
    names: ['NodeJS'],
    logo: '/assets/image/logo/conocimientos/node_js.png',
    alt: 'logo de Node JS',
    width: 454,
    height: 512,
    url: 'https://www.udemy.com/course/nodejs-de-cero-a-experto/',
  }, */
  {
    id: 3,
    names: ["HTML 5"],
    logo: "/assets/image/logo/conocimientos/html.png",
    alt: "logo de HTML",
    width: 2048,
    height: 2048,
    url: "https://youtu.be/-oK6zL01fNM",
  },
  {
    id: 4,
    names: ["CSS 3"],
    logo: "/assets/image/logo/conocimientos/css.png",
    alt: "logo de CSS",
    width: 800,
    height: 800,
    url: "https://youtu.be/K3xmRF8ab1o?si=TnCSUFSA5nbuh4_a",
  },
  {
    id: 5,
    names: ["Sass", "scss"],
    logo: "/assets/image/logo/conocimientos/sass.png",
    alt: "logo de Sass",
    width: 1280,
    height: 960,
    url: "https://sass-lang.com/documentation/",
  },
  {
    id: 6,
    names: ["Tailwind"],
    logo: "/assets/image/logo/conocimientos/tailwind.png",
    alt: "logo de Tailwind",
    width: 360,
    height: 216,
    url: "https://youtu.be/R5EXap3vNDA?si=PUKQuP89JsRNuL7c",
  },
  {
    id: 7,
    names: ["Bootstrap"],
    logo: "/assets/image/logo/conocimientos/bootstrap.webp",
    alt: "logo de Bootstrap",
    width: 960,
    height: 765,
    url: "https://youtu.be/ng8ur8KNrpU?si=s6HhfgqoDqi4qy6l",
  },
  {
    id: 8,
    names: ["UI / UX", "Maquetación Web", "Responsive"],
    logo: "/assets/image/logo/conocimientos/ui_ux.png",
    alt: "logo de UI / UX",
    width: 512,
    height: 512,
    url: "https://youtu.be/udGrXWeJp1Y?si=-mJYkp1ECQIWlFbA",
  },
  {
    id: 9,
    names: ["JavaScript"],
    logo: "/assets/image/logo/conocimientos/javascript.png",
    alt: "logo de JavaScript",
    width: 400,
    height: 400,
    url: "https://www.youtube.com/playlist?list=PLvq-jIkSeTUZ6QgYYO3MwG9EMqC-KoLXA",
  },
  {
    id: 10,
    names: ["TypeScript"],
    logo: "/assets/image/logo/conocimientos/typescript.png",
    alt: "logo de TypeScript",
    width: 512,
    height: 512,
    url: "https://www.udemy.com/course/typescript-guia-completa/",
  },
  {
    id: 11,
    names: ["Ionic"],
    logo: "/assets/image/logo/conocimientos/ionic.webp",
    alt: "logo de Ionic",
    width: 512,
    height: 512,
    url: "https://ionicframework.com/docs",
  },
  {
    id: 12,
    names: ["Capacitor"],
    logo: "/assets/image/logo/conocimientos/capacitor.png",
    alt: "logo de Capacitor",
    width: 300,
    height: 300,
    url: "https://capacitorjs.com/",
  },
  {
    id: 13,
    names: ["Cordova"],
    logo: "/assets/image/logo/conocimientos/cordova.png",
    alt: "logo de Cordova",
    width: 256,
    height: 256,
    url: "https://cordova.apache.org/",
  },
  {
    id: 14,
    names: ["Angular"],
    logo: "/assets/image/logo/conocimientos/angular.png",
    alt: "logo de Angular",
    width: 283,
    height: 300,
    url: "https://www.udemy.com/course/angular-fernando-herrera/",
  },
  {
    id: 15,
    names: ["RxJS"],
    logo: "/assets/image/logo/conocimientos/RxJS.png",
    alt: "logo de RxJS",
    width: 512,
    height: 512,
    url: "https://www.udemy.com/course/angular-fernando-herrera/",
  },
  {
    id: 16,
    names: ["React"],
    logo: "/assets/image/logo/conocimientos/react.png",
    alt: "logo de React JS",
    width: 2300,
    height: 2000,
    url: "https://www.udemy.com/course/react-cero-experto/",
  },
  {
    id: 17,
    names: ["React Native"],
    logo: "/assets/image/logo/conocimientos/react.png",
    alt: "logo de React Native",
    width: 2300,
    height: 2000,
    url: "https://www.udemy.com/course/react-native-expo/",
  },
  {
    id: 18,
    names: ["Expo"],
    logo: "/assets/image/logo/conocimientos/expo.png",
    alt: "logo de Expo",
    width: 295,
    height: 261,
    url: "https://www.udemy.com/course/react-native-expo/",
  },
  {
    id: 19,
    names: ["Next JS"],
    logo: "/assets/image/logo/conocimientos/next.png",
    alt: "logo de Next JS",
    width: 300,
    height: 300,
    url: "https://www.udemy.com/course/nextjs-fh/",
  },
  {
    id: 20,
    names: ["Claude Code"],
    logo: "/assets/image/logo/conocimientos/claude_code.webp",
    alt: "logo de Claude Code",
    width: 3840,
    height: 3840,
    url: "https://www.udemy.com/course/claude-code-guia-completa/",
  },
  {
    id: 21,
    names: ["Consumo de APIs REST"],
    logo: "/assets/image/logo/conocimientos/API.png",
    alt: "logo de API REST",
    width: 512,
    height: 512,
    url: "https://youtu.be/i8sr--1D13Y?si=L4NEHHrhPZKD28nP",
  },
];
