import type { TSkill } from '@/types/portfolio.types';

export const SKILLS: TSkill[] = [
  {
    id: 1,
    names: ['Git'],
    logo: '/assets/image/logo/conocimientos/git.png',
    alt: 'logo de Git',
    url: 'https://www.udemy.com/course/git-github/',
  },
  {
    id: 2,
    names: ['GitHub'],
    logo: '/assets/image/logo/conocimientos/github.png',
    alt: 'logo de GitHub',
    url: 'https://github.com/DanielPinedaM/',
  },
  /* {
    id: 3,
    names: ['NodeJS'],
    logo: '/assets/image/logo/conocimientos/node_js.png',
    alt: 'logo de Node JS',
    url: 'https://www.udemy.com/course/nodejs-de-cero-a-experto/',
  }, */
  {
    id: 3,
    names: ['HTML 5'],
    logo: '/assets/image/logo/conocimientos/html.png',
    alt: 'logo de HTML',
    url: 'https://youtu.be/-oK6zL01fNM',
  },
  {
    id: 4,
    names: ['CSS 3'],
    logo: '/assets/image/logo/conocimientos/css.png',
    alt: 'logo de CSS',
    url: 'https://youtu.be/K3xmRF8ab1o?si=TnCSUFSA5nbuh4_a',
  },
  {
    id: 5,
    names: ['Sass', 'scss'],
    logo: '/assets/image/logo/conocimientos/sass.png',
    alt: 'logo de Sass',
    url: 'https://sass-lang.com/documentation/',
  },
  {
    id: 6,
    names: ['Tailwind'],
    logo: '/assets/image/logo/conocimientos/tailwind.png',
    alt: 'logo de Tailwind',
    url: 'https://youtu.be/R5EXap3vNDA?si=PUKQuP89JsRNuL7c',
  },
  {
    id: 7,
    names: ['Bootstrap'],
    logo: '/assets/image/logo/conocimientos/bootstrap.webp',
    alt: 'logo de Bootstrap',
    url: 'https://youtu.be/ng8ur8KNrpU?si=s6HhfgqoDqi4qy6l',
  },
  {
    id: 8,
    names: ['UI / UX', 'Maquetación Web', 'Responsive'],
    logo: '/assets/image/logo/conocimientos/ui_ux.png',
    alt: 'logo de UI / UX',
    url: 'https://youtu.be/udGrXWeJp1Y?si=-mJYkp1ECQIWlFbA',
  },
  {
    id: 9,
    names: ['JavaScript'],
    logo: '/assets/image/logo/conocimientos/javascript.png',
    alt: 'logo de JavaScript',
    url: 'https://www.youtube.com/playlist?list=PLvq-jIkSeTUZ6QgYYO3MwG9EMqC-KoLXA',
  },
  {
    id: 10,
    names: ['TypeScript'],
    logo: '/assets/image/logo/conocimientos/typescript.png',
    alt: 'logo de TypeScript',
    url: 'https://www.udemy.com/course/typescript-guia-completa/',
  },
  {
    id: 11,
    names: ['Ionic'],
    logo: '/assets/image/logo/conocimientos/ionic.webp',
    alt: 'logo de Ionic',
    url: 'https://ionicframework.com/docs',
  },
  {
    id: 12,
    names: ['Capacitor'],
    logo: '/assets/image/logo/conocimientos/capacitor.png',
    alt: 'logo de Capacitor',
    url: 'https://capacitorjs.com/',
  },
  {
    id: 13,
    names: ['Cordova'],
    logo: '/assets/image/logo/conocimientos/cordova.png',
    alt: 'logo de Cordova',
    url: 'https://cordova.apache.org/',
  },
  {
    id: 14,
    names: ['Angular'],
    logo: '/assets/image/logo/conocimientos/angular.png',
    alt: 'logo de Angular',
    url: 'https://www.udemy.com/course/angular-fernando-herrera/',
  },
  {
    id: 15,
    names: ['RxJS'],
    logo: '/assets/image/logo/conocimientos/RxJS.png',
    alt: 'logo de RxJS',
    url: 'https://www.udemy.com/course/angular-fernando-herrera/',
  },
  {
    id: 16,
    names: ['React'],
    logo: '/assets/image/logo/conocimientos/react.png',
    alt: 'logo de React JS',
    url: 'https://www.udemy.com/course/react-cero-experto/',
  },
  {
    id: 17,
    names: ['Next JS'],
    logo: '/assets/image/logo/conocimientos/next.png',
    alt: 'logo de Next JS',
    url: 'https://www.udemy.com/course/nextjs-fh/',
  },
  {
    id: 18,
    names: ['Claude Code (IA)'],
    logo: '/assets/image/logo/conocimientos/claude_code.webp',
    alt: 'logo de Claude Code',
    url: 'https://www.udemy.com/course/claude-code-guia-completa/',
  },
  {
    id: 19,
    names: ['Consumo de APIs REST'],
    logo: '/assets/image/logo/conocimientos/API.png',
    alt: 'logo de API REST',
    url: 'https://youtu.be/i8sr--1D13Y?si=L4NEHHrhPZKD28nP',
  },
];
